# Generated by Django 4.2.17 on 2025-01-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
