# Generated by Django 4.2.17 on 2025-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_channel', '0003_channel_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='channel',
            name='rank',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
